version: 0.2
phases: 
  build: 
    aws ssm send-command \
    --document-name "AWS-RunShellScript" \
    --parameters 'commands=["echo HelloWorld"]' \
    --targets "Key=instanceids,Values= i-0f3bb189a84f1930f" \
    --comment "echo HelloWorld"
    -script:
     workingDirectory: /home/ubuntu/apache-jmeter-5.4.3/bin
      -sh /home/ubuntu/apache-jmeter-5.4.3/bin/jmeter.sh 
    -script:
        -sh -n -t open-api-load.jmx -l Result.jtl,report.csv
  post_build:
    commands:
      - echo Build completed
