version: 0.2
phases: 
  build: 
    commands :
      aws ssm send-command --profile "$profile" \
            --document-name "AWS-RunPowerShellScript" \
            --targets '[{"Key":"InstanceIds","Values":["'"i-07ebd7e4e98041955"'"]}]' \
            #--parameters '{"commands":["Get-Service -DisplayName \"TimeClockPlus.DynamicWebServer*\" | '"$action"'-Service", "Get-Service -DisplayName \"TimeClockPlus.StaticWebServer*\" | '"$action"'-Service"]}' --query "Command.CommandId" | tr -d '"')
    
    -script:
     workingDirectory: /home/ubuntu/apache-jmeter-5.4.3/bin
      -sh /home/ubuntu/apache-jmeter-5.4.3/bin/jmeter.sh 
    -script:
        -sh -n -t open-api-load.jmx -l Result.jtl,report.csv
  post_build:
    commands:
      - echo Build completed
