version: 0.2
phases: 
  build:    
    -script:
     workingDirectory: /home/ubuntu/apache-jmeter-5.4.3/bin
      -sh /home/ubuntu/apache-jmeter-5.4.3/bin/jmeter.sh 
    commands: -n -t open-api-load.jmx -l Result.jtl
  post_build:
    commands:
      - echo Build completed
